// flow-typed signature: cffe36e20c57fec12431827bc86f60eb
// flow-typed version: <<STUB>>/core-decorators_v^0.15.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'core-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'core-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'core-decorators/lib/applyDecorators' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/autobind' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/core-decorators' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/debounce' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/decorate' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/deprecate' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/enumerable' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/extendDescriptor' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/lazy-initialize' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/memoize' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/mixin' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/nonconfigurable' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/nonenumerable' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/override' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/private/utils' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/readonly' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/suppress-warnings' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/throttle' {
  declare module.exports: any;
}

declare module 'core-decorators/lib/time' {
  declare module.exports: any;
}

declare module 'core-decorators/src/applyDecorators' {
  declare module.exports: any;
}

declare module 'core-decorators/src/autobind' {
  declare module.exports: any;
}

declare module 'core-decorators/src/core-decorators' {
  declare module.exports: any;
}

declare module 'core-decorators/src/debounce' {
  declare module.exports: any;
}

declare module 'core-decorators/src/decorate' {
  declare module.exports: any;
}

declare module 'core-decorators/src/deprecate' {
  declare module.exports: any;
}

declare module 'core-decorators/src/enumerable' {
  declare module.exports: any;
}

declare module 'core-decorators/src/extendDescriptor' {
  declare module.exports: any;
}

declare module 'core-decorators/src/lazy-initialize' {
  declare module.exports: any;
}

declare module 'core-decorators/src/memoize' {
  declare module.exports: any;
}

declare module 'core-decorators/src/mixin' {
  declare module.exports: any;
}

declare module 'core-decorators/src/nonconfigurable' {
  declare module.exports: any;
}

declare module 'core-decorators/src/nonenumerable' {
  declare module.exports: any;
}

declare module 'core-decorators/src/override' {
  declare module.exports: any;
}

declare module 'core-decorators/src/private/utils' {
  declare module.exports: any;
}

declare module 'core-decorators/src/readonly' {
  declare module.exports: any;
}

declare module 'core-decorators/src/suppress-warnings' {
  declare module.exports: any;
}

declare module 'core-decorators/src/throttle' {
  declare module.exports: any;
}

declare module 'core-decorators/src/time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'core-decorators/lib/applyDecorators.js' {
  declare module.exports: $Exports<'core-decorators/lib/applyDecorators'>;
}
declare module 'core-decorators/lib/autobind.js' {
  declare module.exports: $Exports<'core-decorators/lib/autobind'>;
}
declare module 'core-decorators/lib/core-decorators.js' {
  declare module.exports: $Exports<'core-decorators/lib/core-decorators'>;
}
declare module 'core-decorators/lib/debounce.js' {
  declare module.exports: $Exports<'core-decorators/lib/debounce'>;
}
declare module 'core-decorators/lib/decorate.js' {
  declare module.exports: $Exports<'core-decorators/lib/decorate'>;
}
declare module 'core-decorators/lib/deprecate.js' {
  declare module.exports: $Exports<'core-decorators/lib/deprecate'>;
}
declare module 'core-decorators/lib/enumerable.js' {
  declare module.exports: $Exports<'core-decorators/lib/enumerable'>;
}
declare module 'core-decorators/lib/extendDescriptor.js' {
  declare module.exports: $Exports<'core-decorators/lib/extendDescriptor'>;
}
declare module 'core-decorators/lib/lazy-initialize.js' {
  declare module.exports: $Exports<'core-decorators/lib/lazy-initialize'>;
}
declare module 'core-decorators/lib/memoize.js' {
  declare module.exports: $Exports<'core-decorators/lib/memoize'>;
}
declare module 'core-decorators/lib/mixin.js' {
  declare module.exports: $Exports<'core-decorators/lib/mixin'>;
}
declare module 'core-decorators/lib/nonconfigurable.js' {
  declare module.exports: $Exports<'core-decorators/lib/nonconfigurable'>;
}
declare module 'core-decorators/lib/nonenumerable.js' {
  declare module.exports: $Exports<'core-decorators/lib/nonenumerable'>;
}
declare module 'core-decorators/lib/override.js' {
  declare module.exports: $Exports<'core-decorators/lib/override'>;
}
declare module 'core-decorators/lib/private/utils.js' {
  declare module.exports: $Exports<'core-decorators/lib/private/utils'>;
}
declare module 'core-decorators/lib/readonly.js' {
  declare module.exports: $Exports<'core-decorators/lib/readonly'>;
}
declare module 'core-decorators/lib/suppress-warnings.js' {
  declare module.exports: $Exports<'core-decorators/lib/suppress-warnings'>;
}
declare module 'core-decorators/lib/throttle.js' {
  declare module.exports: $Exports<'core-decorators/lib/throttle'>;
}
declare module 'core-decorators/lib/time.js' {
  declare module.exports: $Exports<'core-decorators/lib/time'>;
}
declare module 'core-decorators/src/applyDecorators.js' {
  declare module.exports: $Exports<'core-decorators/src/applyDecorators'>;
}
declare module 'core-decorators/src/autobind.js' {
  declare module.exports: $Exports<'core-decorators/src/autobind'>;
}
declare module 'core-decorators/src/core-decorators.js' {
  declare module.exports: $Exports<'core-decorators/src/core-decorators'>;
}
declare module 'core-decorators/src/debounce.js' {
  declare module.exports: $Exports<'core-decorators/src/debounce'>;
}
declare module 'core-decorators/src/decorate.js' {
  declare module.exports: $Exports<'core-decorators/src/decorate'>;
}
declare module 'core-decorators/src/deprecate.js' {
  declare module.exports: $Exports<'core-decorators/src/deprecate'>;
}
declare module 'core-decorators/src/enumerable.js' {
  declare module.exports: $Exports<'core-decorators/src/enumerable'>;
}
declare module 'core-decorators/src/extendDescriptor.js' {
  declare module.exports: $Exports<'core-decorators/src/extendDescriptor'>;
}
declare module 'core-decorators/src/lazy-initialize.js' {
  declare module.exports: $Exports<'core-decorators/src/lazy-initialize'>;
}
declare module 'core-decorators/src/memoize.js' {
  declare module.exports: $Exports<'core-decorators/src/memoize'>;
}
declare module 'core-decorators/src/mixin.js' {
  declare module.exports: $Exports<'core-decorators/src/mixin'>;
}
declare module 'core-decorators/src/nonconfigurable.js' {
  declare module.exports: $Exports<'core-decorators/src/nonconfigurable'>;
}
declare module 'core-decorators/src/nonenumerable.js' {
  declare module.exports: $Exports<'core-decorators/src/nonenumerable'>;
}
declare module 'core-decorators/src/override.js' {
  declare module.exports: $Exports<'core-decorators/src/override'>;
}
declare module 'core-decorators/src/private/utils.js' {
  declare module.exports: $Exports<'core-decorators/src/private/utils'>;
}
declare module 'core-decorators/src/readonly.js' {
  declare module.exports: $Exports<'core-decorators/src/readonly'>;
}
declare module 'core-decorators/src/suppress-warnings.js' {
  declare module.exports: $Exports<'core-decorators/src/suppress-warnings'>;
}
declare module 'core-decorators/src/throttle.js' {
  declare module.exports: $Exports<'core-decorators/src/throttle'>;
}
declare module 'core-decorators/src/time.js' {
  declare module.exports: $Exports<'core-decorators/src/time'>;
}
