// flow-typed signature: e14440fc5b7c7eff2771d5ec572e46d2
// flow-typed version: <<STUB>>/refactoring-codemods_v0.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'refactoring-codemods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'refactoring-codemods' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'refactoring-codemods/lib/index' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/fileHelpers/ensureDotSlash' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/fileHelpers/filterMatchingPaths' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/fileHelpers/index' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/fileHelpers/isRelativePath' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/fileHelpers/removeExtension' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/import-declaration-transform' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/import-relative-transform' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/import-specifier-transform' {
  declare module.exports: any;
}

declare module 'refactoring-codemods/lib/transformers/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'refactoring-codemods/lib/index.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/index'>;
}
declare module 'refactoring-codemods/lib/transformers/fileHelpers/ensureDotSlash.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/fileHelpers/ensureDotSlash'>;
}
declare module 'refactoring-codemods/lib/transformers/fileHelpers/filterMatchingPaths.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/fileHelpers/filterMatchingPaths'>;
}
declare module 'refactoring-codemods/lib/transformers/fileHelpers/index.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/fileHelpers/index'>;
}
declare module 'refactoring-codemods/lib/transformers/fileHelpers/isRelativePath.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/fileHelpers/isRelativePath'>;
}
declare module 'refactoring-codemods/lib/transformers/fileHelpers/removeExtension.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/fileHelpers/removeExtension'>;
}
declare module 'refactoring-codemods/lib/transformers/import-declaration-transform.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/import-declaration-transform'>;
}
declare module 'refactoring-codemods/lib/transformers/import-relative-transform.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/import-relative-transform'>;
}
declare module 'refactoring-codemods/lib/transformers/import-specifier-transform.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/import-specifier-transform'>;
}
declare module 'refactoring-codemods/lib/transformers/index.js' {
  declare module.exports: $Exports<'refactoring-codemods/lib/transformers/index'>;
}
